# Stage 1: build
FROM node:24-alpine AS builder
RUN npm config set registry https://registry.npmmirror.com

WORKDIR /app

COPY . .
RUN npm install
RUN npm run build

# Stage 2: nginx
FROM nginx:alpine

COPY nginx.docker.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]