server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location /avatar/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /avatar/index.html;
    }
}