server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name beetector.pro www.beetector.pro;

    ssl_certificate     /etc/ssl/beetector.pro/certificate.crt;
    ssl_certificate_key /etc/ssl/beetector.pro/certificate.key;

    client_max_body_size 15M;

    gzip on;

    # =========================
    # FRONTEND (Vue/Vite SPA)
    # =========================
    location /avatar/ {
        root /var/www/avatar-frontend;
        index index.html;

        try_files $uri $uri/ /avatar/index.html;
    }

    # =========================
    # API (FastAPI)
    # =========================
    location /api-avatar/ {
        proxy_pass http://127.0.0.1:9000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # если хочешь оставить старый /api тоже:
    # location /api/ {
    #     proxy_pass http://127.0.0.1:9000;

    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # }

    # =========================
    # DOCS
    # =========================
    # location /docs {
    #     proxy_pass http://127.0.0.1:9000;

    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # }

    # location /openapi.json {
    #     proxy_pass http://127.0.0.1:9000;

    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }
}

# ln -s /var/www/avatar-gpt/backend/avatar.nginx.conf /etc/nginx/sites-enabled/avatar.nginx.conf
# ln -s /var/www/avatar-gpt/backend/avatar.nginx.conf /etc/nginx/sites-available/avatar.nginx.conf
